---
- name: "Provision Nvidia GPU AMI"
  hosts: default
  become: true

  vars_files:
    - vars/nvidia-base.yml

  pre_tasks:
    - name: Ensure dependencies are installed.
      apt:
        name:
          - sudo
          - openssh-server
        state: present


  roles:
    - role: geerlingguy.security
      tags: ['security']

    - role: nvidia.nvidia_driver
      tags: ['nvidia']
